import type { Capability, TeloRole } from '@/types/auth';

/**
 * Emergency / seed defaults for Telo role→capability grants and the
 * LIS-usertype→Telo-role map. Live data lives in dbo.telo_role* tables;
 * these constants seed those tables and backstop Redis/DB failures.
 *
 * Keep in sync with db/sql/108_seed_telo_roles.sql.
 */

export const ROLE_CAPS: Record<string, Capability[]> = {
  super_admin: [
    'user:manage',
    'order:create',
    'order:accession',
    'order:view',
    'order:b2c',
    'order:b2b',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'payment:refund',
    'rate:view',
    'rate:manage',
    'balance:view',
    'account:view',
    'account:manage',
    'sales:view',
    'dashboard:view',
    'report:view',
  ],
  admin: [
    'order:create',
    'order:accession',
    'order:view',
    'order:b2c',
    'order:b2b',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'rate:view',
    'rate:manage',
    'balance:view',
    'account:view',
    'sales:view',
    'dashboard:view',
  ],
  billing: [
    'order:create',
    'order:accession',
    'order:view',
    'order:b2c',
    'order:b2b',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'rate:view',
    'balance:view',
    'dashboard:view',
  ],
  b2c_billing: [
    'order:create',
    'order:accession',
    'order:view',
    'order:b2c',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'rate:view',
    'balance:view',
    'dashboard:view',
  ],
  b2b_billing: [
    'order:create',
    'order:accession',
    'order:view',
    'order:b2b',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'rate:view',
    'balance:view',
    'account:view',
    'sales:view',
    'dashboard:view',
  ],
  client: [
    'order:create',
    'order:accession',
    'order:view',
    'order:b2c',
    'order:b2b',
    'order:discount',
    'patient:create',
    'patient:view',
    'bill:view',
    'payment:capture',
    'rate:view',
    'balance:view',
    'account:view',
    'sales:view',
    'dashboard:view',
  ],
  client_reporting: ['report:view'],
  report_admin: ['report:view'],
  technician: [
    'order:accession',
    'order:view',
    'order:b2c',
    'patient:view',
  ],
  viewer: [
    'order:view',
    'order:b2c',
    'patient:view',
    'bill:view',
    'rate:view',
    'balance:view',
    'account:view',
    'sales:view',
    'dashboard:view',
  ],
};

export const LIS_TO_TELO_ROLE_MAP: Record<number, TeloRole> = {
  1: 'super_admin',
  5: 'admin',
  26: 'admin',
  28: 'admin',
  32: 'admin',
  2: 'b2b_billing',
  7: 'b2b_billing',
  12: 'b2b_billing',
  29: 'billing',
  33: 'billing',
  4: 'technician',
  9: 'technician',
  16: 'technician',
  17: 'technician',
  18: 'technician',
  20: 'technician',
  25: 'technician',
  30: 'technician',
  34: 'technician',
};

export const BUILTIN_TELO_ROLES = Object.keys(ROLE_CAPS) as TeloRole[];
