USE [master]
GO

/****** Object:  Database [Noble]    Script Date: 15/05/2026 07:43:08 ******/
CREATE DATABASE [Noble]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Noble', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Noble.mdf' , SIZE = 152377088KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Noble_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Noble_log.ldf' , SIZE = 3164032KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Noble].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Noble] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Noble] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Noble] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Noble] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Noble] SET ARITHABORT OFF 
GO

ALTER DATABASE [Noble] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Noble] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Noble] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Noble] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Noble] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Noble] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Noble] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Noble] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Noble] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Noble] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Noble] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Noble] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Noble] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Noble] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Noble] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Noble] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Noble] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Noble] SET RECOVERY FULL 
GO

ALTER DATABASE [Noble] SET  MULTI_USER 
GO

ALTER DATABASE [Noble] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Noble] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Noble] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Noble] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Noble] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Noble] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Noble] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Noble] SET  READ_WRITE 
GO

